devJaem/sktrello

.eslintrc.js, src/board/entities/board-user.entity.ts, src/board/entities/board.entity.ts
closed #6 
- board의 entity 작성을 완료하였습니다.
=> 🎉feat:board-entity

.eslintrc.js, src/comment/entities/comment.entity.ts
=> 🎉 feat : comment entity

.eslintrc.js, src/user/entities/user.entity.ts
feat user entity
closed #4 
user entity를 만들었습니다. ERD 상의 관계를 감안하여 주석처리해 미리 만든 코드가 있는데, 이 부분 한 번 체크해주시면 더 좋을 것 같습니다(아직 확신이 적어요 ㅎㅎ)
=> 🎉feat:user entity

.eslintrc.js, src/list/entities/list.entity.ts, src/list/list.module.ts
closed #3 
- list의 entity 작성했습니다.
=> 🎉feat:list-entity

src/card/entities/card-user.entity.ts, src/card/entities/card.entity.ts
=> 🎉 feat:card-entity

package-lock.json, package.json, src/app.module.ts, src/board/board.module.ts, src/board/entities/board-user.entity.ts, src/board/entities/board.entity.ts, src/board/types/board-user.type.ts, src/card/card.module.ts, src/card/entities/card-user.entity.ts, src/card/entities/card.entity.ts, src/card/types/duedate-status.type.ts, src/check_item/check_item.module.ts, src/check_item/entities/check_item.entity.ts, src/check_list/check_list.module.ts, src/check_list/entities/check_list.entity.ts, src/comment/comment.module.ts, src/comment/entities/comment.entity.ts, src/list/entities/list.entity.ts, src/user/entities/user.entity.ts, src/user/user.module.ts, tsconfig.json
=> 🎉 feat: entity init

src/board/board.controller.ts, src/board/board.module.ts, src/board/board.service.ts, src/board/dto/create-board.dto.ts, src/board/dto/invite-board-member.dto.ts, src/board/dto/update-board.dto.ts, src/board/entities/board-user.entity.ts, src/board/entities/board.entity.ts, src/card/entities/card-user.entity.ts, src/card/entities/card.entity.ts, src/check_item/entities/check_item.entity.ts, src/check_list/entities/check_list.entity.ts, src/constants/message.constants.ts, src/list/entities/list.entity.ts, src/user/entities/user.entity.ts, src/utils/test-user.decorator.ts
cloase #18 
- relation 관련 일부 잘못된 부분 (카멜케이스 미적용, 단수/복수 실수) 수정 및 주석 추가
- Board (Module / Controller / Service) CRUD API 구현 + 보드 멤버 초대 API 구현
=> 🎉feat: Board - Module/Controller/Service - CRUD + 보드멤버초대

nest-cli.json, package-lock.json, package.json, src/constants/message.constants.ts, src/list/dto/create-list.dto.ts, src/list/dto/move-list.dto.ts, src/list/dto/update-list.dto.ts, src/list/entities/list.entity.ts, src/list/list.controller.ts, src/list/list.module.ts, src/list/list.service.ts, src/utils/lexorank.ts, src/utils/user.decorator.ts
closed #21 
- List CRUD API 구현
- List 순서 이동 API 구현을 위해 **LexoRank 패키지 설치** > git pull 시 `npm install` 해야 함 !
- JWT 인증된 사용자 여부 확인을 위해 임시로 user 데코레이터 파일 생성함 (`src/utils/user.decorator`)
: 사용자 관리 기능 구현 완료되면 수정 예정
- List 조회 시 해당 List에 있는 Card 정보 가져와야 함
: 카드 관리 기능 구현 완료되면 수정 예정
[npm lexorank](https://www.npmjs.com/package/lexorank/v/1.0.1)
https://github.com/kvandake/lexorank-ts
[YouTube - JIRA lexorank explained](https://youtu.be/OjQv9xMoFbg?si=4Su7VQoUxi9eo9Pe)
[Jira의 이슈 정렬 방식이 Integer 방식이 아니라고?!](https://techblog.lycorp.co.jp/ko/about-atlassian-jira-ranking-algorithm-lexorank)
[[Nest.js] LexoRank를 이용하여 카드 이동 구현](https://velog.io/@wlduq0150/Nest.js-LexoRank를-이용하여-카드-이동-구현)
[어플리케이션에서 LexoRank 모듈이 정말 유용한 이유](https://velog.io/@ksi05503/당신의-어플리케이션-로직에-LexoRank-를-적용해야하는-이유)
=> 🎉feat: List - CRUD 구현

src/comment/comment.controller.ts, src/comment/comment.service.ts, src/comment/dto/create-comment.dto.ts, src/constants/comment.message.constants.ts
closed #26 
- 댓글 컨트롤러, 서비스, 메시지 코드 추가
- 댓글 생성, 조회, 상세조회, 수정, 삭제 기능 추가
- 메시지 코드 파일 생성 및 추가
컨트롤러에 ParseIntPipe 코드는 자동으로 숫자로 변환 시켜주는 역할을한다.
board  코드는 풀 땡겨옴
=> 🎉feat: Comment - CRUD 구현

src/comment/comment.controller.ts, src/comment/comment.service.ts
closed #52
- 댓글 삭제 시 에러 500번 뜨는 것 수정
- userid 하드 코딩 부분 수정 주석추가
=> [FEATURE][Comment][D예외처리]

src/list/dto/create-list.dto.ts, src/list/dto/move-list.dto.ts, src/list/dto/update-list.dto.ts, src/list/list.controller.ts, src/list/list.service.ts
closed #40 #42 
- List endpoint 수정
- List 생성 시 생성된 list가 삽입되는 위치 결정 (lexorank)
- Swagger 재설정
=> ✨ update: List - endpoint 수정, 생성된 list 위치 결정, swagger 적용

src/user/dto/sign-in.dto.ts, src/user/dto/sign-up.dto.ts, src/user/user.controller.ts
=> chore : add Api sample for swagger

src/board/board.controller.ts, src/card/card.controller.ts, src/checkitem/checkitem.controller.ts, src/checklist/checklist.controller.ts, src/comment/comment.controller.ts, src/list/list.controller.ts, src/user/user.controller.ts
=> 🎉fix: 누락된 데코레이터 추가

src/checkitem/dto/create-checkitem.dto.ts, src/checkitem/dto/move-checkitem.dto.ts, src/checkitem/dto/update-checkitem.dto.ts, src/checklist/dto/create-checklist.dto.ts, src/constants/check-message.constant.ts
=> update: 오탈자 수정

src/auth/guard/board-user-roles.guard.ts, src/board/board.controller.ts
closed #65 
- roles 가드 권한 인식이 되지 않는 버그 해결
=> 🎉fix: roles가드 권한 인식이 되지 않는 버그 해결

src/card/card.controller.ts, src/card/card.service.ts, src/card/dto/create-card.dto.ts, src/card/dto/move-card.dto.ts, src/card/dto/update-card.dto.ts, src/checkitem/checkitem.service.ts, src/checklist/checklist.controller.ts, src/list/dto/create-list.dto.ts, src/list/list.controller.ts, src/list/list.module.ts, src/list/list.service.ts, src/utils/lexorank.ts
=> 🎉fix: 1차테스트 및 버그 수정

src/comment/comment.controller.ts
closed #72 
- comment  controller 에 유저 아이디 login-decorator로 수정함
=> 🩹 fix: Comment - login-decorator

src/list/dto/create-list.dto.ts, src/list/list.service.ts, src/utils/lexorank.ts
closed #80 
- 위치 관련 dto, service 수정
- List 생성 시 toPrevId, toNextId 입력하지 않도록 수정
- List 이름 수정 시 title 입력하지 않도록 수정
=> 🐛bugfix: List - 위치 관련 dto, service 수정

src/card/card.controller.ts, src/card/card.service.ts
closed #76 
- 🩹 fix : cardmove
=> 76 fixcardmovecard

src/board/board.controller.ts, src/board/board.service.ts, src/board/dto/board-auth.dto.ts, src/constants/board-message.constant.ts, src/user/dto/sign-in.dto.ts, src/user/dto/sign-up.dto.ts, src/user/user.service.ts
- 보드 초대 수락 API,
- 보드 초대 거절 API, 
- 보드 사용자 권한 변경 API, 
- 보드 목록 조회 API 간결하게 리팩토링
=> feat: 보드 초대 수락/거절 API, 보드 사용자 권한 변경 API 등

src/checkitem/checkitem.controller.ts, src/checkitem/checkitem.module.ts, src/checkitem/checkitem.service.ts, src/checkitem/dto/create-checkitem.dto.ts, src/constants/check-message.constant.ts
=> ♻️ refactor: checkItem endpoint

src/constants/user-message.constant.ts, src/user/user.controller.ts, src/user/user.service.ts
=> 🎉feat: 회원 탈퇴 API

src/comment/comment.controller.ts, src/comment/comment.module.ts, src/comment/comment.service.ts, src/utils/elapsedtime.ts
closed #78
- userId 조회 대신 닉네임 조회로 수정
- n분 전, n시간 전, n일 전(수정됨)으로 나타나게 표현하기(시간경과)
- Service 파일 조회 부분 수정
- src/utils/elapsedtime (시간경과 함수생성 파일)
- 앤드포인트 수정
- @UseGuards() 수정
=> 🩹 fix : comment 조회 수정

src/checkitem/checkitem.controller.ts, src/checkitem/checkitem.module.ts, src/checklist/checklist.controller.ts, src/checklist/checklist.module.ts
=> ♻️refactor: CheckLst endpoint

src/board/board.controller.ts, src/board/board.service.ts
=> 🎉fix: 가드 데코레이터 누락 보충

src/card/card.service.ts, src/list/list.service.ts
- ♻️refactor: List - 상세 조회 시 Card 정보 불러오기 (순서 반영)
=> ♻️refactor: List - 상세 조회 시 Card 정보 불러오기 (순서 반영)

src/comment/comment.controller.ts
closed #99 
- comment 삭제부분 앤드포인트 수정
=> 🩹 fix : comment 삭제부분 앤드포인트 수정

src/checkitem/dto/create-checkitem.dto.ts, src/constants/check-message.constant.ts
=> Revert "hotfix: 오탈자, format 수정, 대소분자 변경"

src/checkList/checkList.controller.ts, src/checkList/checkList.module.ts, src/checkList/checkList.service.ts, src/checkList/dto/create-checkList.dto.ts, src/checkList/dto/update-checkList.dto.ts, src/checkList/entities/checkList.entity.ts
=> Revert "Delete src/checkList directory"

src/checkItem/checkItem.controller.ts, src/checkItem/checkItem.module.ts, src/checkItem/checkItem.service.ts, src/checkItem/dto/create-checkItem.dto.ts, src/checkItem/dto/move-checkItem.dto.ts, src/checkItem/dto/update-checkItem.dto.ts, src/checkItem/entities/checkItem.entity.ts
=> Revert "Delete src/checkItem directory"
